# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "35d76dcad2f7b221516c15d970a8b129"
name = "WebCheque Payments"
application_url = "https://rwanda-zoning-viewpicture-mime.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-48fd5bcc.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers,write_orders,write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://rwanda-zoning-viewpicture-mime.trycloudflare.com/auth/callback",
  "https://rwanda-zoning-viewpicture-mime.trycloudflare.com/auth/shopify/callback",
  "https://rwanda-zoning-viewpicture-mime.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://sgw-develop.webcheque.com.br/webhooks"
  customer_data_request_url = "https://sgw-develop.webcheque.com.br/webhooks"
  shop_deletion_url = "https://sgw-develop.webcheque.com.br/webhooks"

[app_proxy]
url = "https://rwanda-zoning-viewpicture-mime.trycloudflare.com/api/proxy"
subpath = "store-pickup"
prefix = "apps"

[pos]
embedded = false

[app_preferences]
url = "https://www.app.example.com/preferences"
