apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: webcheque-shopify-gateway-develop-pdb
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: webcheque-shopify-gateway-develop
